//! Mock MCP server helpers for testing.
//!
//! Provides utilities to spawn in-process mock MCP servers that advertise
//! configurable tools and return configurable results.

#![allow(dead_code, clippy::unused_self, clippy::missing_const_for_fn)]

use std::collections::{HashMap, HashSet};
use std::sync::Arc;

use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::model::{ServerCapabilities, ServerInfo};
use rmcp::{ServerHandler, tool, tool_handler, tool_router};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Input for the echo tool.
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct EchoInput {
    /// The text to echo back.
    pub text: String,
}

/// Empty input payload for no-arg mock tools.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct EmptyInput {}

const DEFAULT_TOOL_NAME: &str = "echo";
const KNOWN_TOOL_NAMES: &[&str] = &[
    "echo",
    "search_files",
    "read_file",
    "tool_a",
    "tool_b",
    "tool_c",
    "tool_d",
];

/// Configuration for a single mock tool.
#[derive(Debug, Clone)]
pub struct MockToolDef {
    /// Tool name as advertised by the mock server.
    pub name: String,
    /// Tool description.
    pub description: String,
    /// JSON Schema for the tool's input parameters.
    pub input_schema: Value,
    /// The result text to return when this tool is called.
    pub result_text: String,
    /// Whether the result should be marked as an error.
    pub is_error: bool,
}

impl MockToolDef {
    /// Create a simple mock tool that returns text.
    pub fn simple(name: &str, result_text: &str) -> Self {
        Self {
            name: name.to_string(),
            description: format!("Mock tool: {name}"),
            input_schema: serde_json::json!({
                "type": "object",
                "properties": {},
            }),
            result_text: result_text.to_string(),
            is_error: false,
        }
    }

    /// Create a mock tool with a specified input schema.
    pub fn with_schema(name: &str, schema: Value, result_text: &str) -> Self {
        Self {
            name: name.to_string(),
            description: format!("Mock tool: {name}"),
            input_schema: schema,
            result_text: result_text.to_string(),
            is_error: false,
        }
    }

    /// Create a mock tool that returns an error.
    pub fn error(name: &str, error_text: &str) -> Self {
        Self {
            name: name.to_string(),
            description: format!("Mock error tool: {name}"),
            input_schema: serde_json::json!({
                "type": "object",
                "properties": {},
            }),
            result_text: error_text.to_string(),
            is_error: true,
        }
    }
}

/// Configuration for a mock MCP server.
#[derive(Debug, Clone)]
pub struct MockServerConfig {
    /// Tools to advertise.
    pub tools: Vec<MockToolDef>,
    /// Custom tool results keyed by tool name.
    pub custom_results: HashMap<String, MockToolDef>,
}

impl MockServerConfig {
    /// Create a mock server config with the given tools.
    pub fn new(tools: Vec<MockToolDef>) -> Self {
        Self {
            tools,
            custom_results: HashMap::new(),
        }
    }

    /// Create an empty mock server config (no tools).
    pub fn empty() -> Self {
        Self {
            tools: Vec::new(),
            custom_results: HashMap::new(),
        }
    }
}

/// A mock MCP server that advertises configurable tools.
///
/// Uses rmcp's tool macro system to implement `ServerHandler`.
#[derive(Debug, Clone)]
pub struct MockMcpServer {
    /// Map of tool name to (result text, is error).
    results: Arc<HashMap<String, (String, bool)>>,
    /// Tool router generated by rmcp macros.
    tool_router: ToolRouter<Self>,
}

impl MockMcpServer {
    pub fn from_config(config: &MockServerConfig) -> Self {
        let enabled_tools = if config.tools.is_empty() {
            vec![DEFAULT_TOOL_NAME.to_string()]
        } else {
            config.tools.iter().map(|tool| tool.name.clone()).collect()
        };
        let enabled_tool_set: HashSet<_> = enabled_tools.iter().cloned().collect();
        let unknown_tools: Vec<_> = enabled_tool_set
            .iter()
            .filter(|name| !KNOWN_TOOL_NAMES.contains(&name.as_str()))
            .cloned()
            .collect();
        assert!(
            unknown_tools.is_empty(),
            "unknown mock MCP tools requested: {unknown_tools:?}; supported tools: {KNOWN_TOOL_NAMES:?}"
        );

        let mut results = HashMap::new();
        for tool_def in &config.tools {
            results.insert(
                tool_def.name.clone(),
                (tool_def.result_text.clone(), tool_def.is_error),
            );
        }
        let mut tool_router = Self::tool_router();
        for tool_name in KNOWN_TOOL_NAMES {
            if !enabled_tool_set.contains(*tool_name) {
                tool_router.remove_route(tool_name);
            }
        }
        Self {
            results: Arc::new(results),
            tool_router,
        }
    }

    fn text_result(&self, tool_name: &str, default: impl Into<String>) -> String {
        self.results
            .get(tool_name)
            .map_or_else(|| default.into(), |(result, _)| result.clone())
    }
}

#[tool_router]
impl MockMcpServer {
    /// A generic echo tool for testing — returns whatever text it receives.
    #[tool(description = "Echo the input back")]
    async fn echo(&self, Parameters(input): Parameters<EchoInput>) -> String {
        self.text_result("echo", input.text)
    }

    #[tool(description = "Mock search_files tool")]
    async fn search_files(&self, Parameters(_input): Parameters<EmptyInput>) -> String {
        self.text_result("search_files", "found: main.rs")
    }

    #[tool(description = "Mock read_file tool")]
    async fn read_file(&self, Parameters(_input): Parameters<EmptyInput>) -> String {
        self.text_result("read_file", "contents of file")
    }

    #[tool(description = "Mock tool A")]
    async fn tool_a(&self, Parameters(_input): Parameters<EmptyInput>) -> String {
        self.text_result("tool_a", "tool_a")
    }

    #[tool(description = "Mock tool B")]
    async fn tool_b(&self, Parameters(_input): Parameters<EmptyInput>) -> String {
        self.text_result("tool_b", "tool_b")
    }

    #[tool(description = "Mock tool C")]
    async fn tool_c(&self, Parameters(_input): Parameters<EmptyInput>) -> String {
        self.text_result("tool_c", "tool_c")
    }

    #[tool(description = "Mock tool D")]
    async fn tool_d(&self, Parameters(_input): Parameters<EmptyInput>) -> String {
        self.text_result("tool_d", "tool_d")
    }
}

#[tool_handler(router = self.tool_router)]
impl ServerHandler for MockMcpServer {
    fn get_info(&self) -> ServerInfo {
        let mut info = ServerInfo::default();
        info.instructions = Some("Mock MCP server for testing".into());
        info.capabilities = ServerCapabilities::builder().enable_tools().build();
        info
    }
}

/// Spawn an in-process MCP server and connect a client, returning the running client service.
///
/// Uses `tokio::io::duplex()` to create an in-memory bidirectional channel.
pub async fn spawn_mock_server_with_client(
    config: &MockServerConfig,
) -> rmcp::service::RunningService<rmcp::service::RoleClient, rmcp::model::ClientInfo> {
    use rmcp::service::ServiceExt;

    let server = MockMcpServer::from_config(config);

    // Create in-memory duplex streams.
    let (client_stream, server_stream) = tokio::io::duplex(4096);

    // Spawn the server on one end of the duplex.
    // We must keep the RunningService alive (via .waiting()) or the server drops immediately.
    let _server_handle = tokio::spawn(async move {
        if let Ok(svc) = server.serve(server_stream).await {
            let _ = svc.waiting().await;
        }
    });

    // Connect the client on the other end.
    rmcp::model::ClientInfo::default()
        .serve(client_stream)
        .await
        .expect("client connection should succeed")
}

/// Spawn an in-process MCP server and return a fully-formed `McpConnection`.
///
/// This creates an in-memory duplex, spawns the mock server, connects a client,
/// and wraps it in an `McpConnection` with tool discovery already performed.
pub async fn spawn_mock_connection(
    server_name: &str,
    tool_prefix: Option<&str>,
    mock_tools: Vec<MockToolDef>,
) -> swink_agent_mcp::McpConnection {
    let mock_config = MockServerConfig::new(mock_tools);
    let service = spawn_mock_server_with_client(&mock_config).await;

    let mcp_config = swink_agent_mcp::McpServerConfig {
        name: server_name.to_string(),
        transport: swink_agent_mcp::McpTransport::Stdio {
            command: "mock".into(),
            args: vec![],
            env: HashMap::default(),
        },
        tool_prefix: tool_prefix.map(String::from),
        tool_filter: None,
        requires_approval: false,
        connect_timeout_ms: None,
        discovery_timeout_ms: None,
    };

    swink_agent_mcp::McpConnection::from_service(mcp_config, service, None)
        .await
        .expect("mock connection should succeed")
}
